version: '2'

networks:
  hyperlink:

services:
  insurance-ca:
    container_name: insurance-ca
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=insurance-ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b insuranceApp-admin:insuranceApp-adminpw -d'
    volumes:
      - ./insuranceCA/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - hyperlink

  shop-ca:
    container_name: shop-ca
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=shop-ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b insuranceApp-admin:insuranceApp-adminpw -d'
    
    volumes:  
      - ./shopCA/ca/:/etc/hyperledger/fabric-ca-server-config 
    networks:
      - hyperlink

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050
    networks:
      - hyperlink

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0
    networks:
      - hyperlink

  shop-peer:
    container_name: shop-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: shop-peer
    environment:
    - CORE_PEER_ID=shop-peer
    - CORE_PEER_ADDRESS=shop-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=shop-peer:7051
    - CORE_PEER_LOCALMSPID=ShopOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - insurance-peer
    networks:
      - hyperlink
      
  cli:
   container_name: cli
   image: hyperledger/fabric-tools
   tty: true
   environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=insurance-peer:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurnace-org/users/Admin@insurance-org/msp
    - CORE_CHAINCODE_KEEPALIVE=10
   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
   command: /bin/bash
   volumes:
    - /var/run/:/host/var/run/
    - ./web/chaincode/:/opt/gopath/src/chaincode/
    - ./cli/peer:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    - ./cli/peer:/etc/hyperledger/configtx
   networks:
    - hyperlink


  web:
    container_name: web
    image: web
    environment:
    - PORT=3000
    - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
    - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:latest
    ports:
    - 3000:3000
    volumes:
    - /var/run/:/host/var/run/
    depends_on:
    - orderer0
    - insurance-ca
    - insurance-peer
    - shop-ca
    - shop-peer
    stdin_open: true
    tty: true
    networks:
    - hyperlink